pkg_list:
  - bash-completion
  - bind-utils
  - chrony
  - conntrack
  - curl
  - dstat
  - file
  - glances
  - htop
  - iftop
  - iproute
  - ipset
  - iptables
  - ipvsadm
  - jq
  - less
  - libseccomp
  - mlocate
  - mtr
  - net-tools
  - nload
  - nmap
  - nmap-ncat
  - procps
  - screen
  - sysstat
  - telnet
  - traceroute
  - tree
  - unzip
  - vim
  - wget
  - which
  - yum-utils
  - redis
  - certbot
  - gcc
  - cronie
  - crontabs
  - python3-pip
  - rsync
  - openssl
  - libselinux-python3
  - firewalld

user_list:
  - jms-admin
  - jms-op
  - jms-superop
