---

- name: Import RPM-GPG-KEY-elrepo
  rpm_key:
    state: present
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
#    state: absent
#    key: BAADAE52

- name: Add elrepo.repo
  dnf:
    name: https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
#    name: https://www.elrepo.org/elrepo-release-8.1-1.el8.elrepo.noarch.rpm
    state: present
    validate_certs: no

- name: Disable elrepo
  ini_file:
    dest: /etc/yum.repos.d/elrepo.repo
    section: "elrepo"
    option: 'enabled'
    value: '0'
    no_extra_spaces: yes

- name: Remove kernel-headers
  dnf:
    name: kernel-headers
    state: absent
    skip_broken: yes

- name: Install kernel-lt
  dnf:
    name:
    - 'kernel-lt'
    - 'kernel-lt-devel'
    - 'kernel-lt-headers'
    state: present
    enablerepo: elrepo-kernel
    disable_excludes: all
  notify: ["Reboot system"]

- name: "Set grub2 default"
  shell: grub2-set-default 0
  notify: ["Reboot system"]
  ignore_errors: True
